name: Continuous Deployment

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: Debbuging Project
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore APIEnem.API
    - name: Build Project
      run: dotnet build APIEnem.API

  deploy: 
    name: Deploy Project in Heroku
    runs-on: ubuntu-latest
    environment: Produção
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "apienem"
          heroku_email: "otaviovb.developer@gmail.com"
          usedocker: true