name: Continuous Integration

on: [pull_request]

jobs:
  build:
    name: Debbuging Project
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore APIEnem.API
    - name: Build Project
      run: dotnet build APIEnem.API

  tests:
    name: Doing Domain Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: dotnet test APIEnem.DomainTests
